networks:
  beacon-dev:
    external: true

services:
  ian_admin:
    container_name: ian_admin
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/app:cached
    command: sleep infinity
    networks:
      - beacon-dev

volumes:
  vscode_extensions:
    external: true
  vscode_data:
    external: true
